inherit_from: .rubocop_todo.yml
AllCops:
  # Only runs checks on specific directories. Could be expanded to
  # include more directories.
  TargetRubyVersion: 2.3

  Exclude:
    - Capfile
    - Gemfile
    - Guardfile
    - Rakefile
    - '**/*.sh'
    - '**/*.bash'
    - '**/*.yml'
    - '**/*.txt'
    - '**/*.md'
    - 'bin/setup'
    - 'bin/update'
    - 'bin/spring'
    - config/boot.rb
    - db/schema.rb
    - db/migrate/**/*
    - spec/*.opts
    - tmp/**/*
    - vendor/**/*
    - log/**/*
    - lib/tasks/mau.rake
    - lib/tasks/debug.rake
    - app/lib/app_config.rb
    - config/initializers/setup_email_lists.rb
    - features/step_definitions/factory_steps.rb

Rails:
  Enabled: true

Lint/HandleExceptions:
  Exclude:
    - app/services/search/indexer.rb

Metrics/AbcSize:
  Max: 38

Metrics/BlockLength:
  Max: 151
  Exclude:
    - config/routes.rb

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 9

Naming/AccessorMethodName:
  Exclude:
    - app/models/concerns/address_mixin.rb

Naming/ConstantName:
  Exclude:
    - config/application.rb

Naming/MemoizedInstanceVariableName:
  Exclude:
    - app/controllers/**/*.rb
    - spec/support/**/*.rb

Rails/FilePath:
  Exclude:
    - config/environments/test.rb

Rails/DynamicFindBy:
  Exclude:
    - app/models/user_session.rb

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/Output:
  Exclude:
    - config/environments/test.rb
    - 'db/sample_data.rb'
    - 'db/sample_data/**/*'

Rails/OutputSafety:
  Enabled: false

Rails/TimeZone:
  Exclude:
    - tztest.rb

Rails/DynamicFindBy:
  Exclude:
    - app/models/user_session.rb

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf
  SupportedStyles:
    - sprintf
    - format

Style/RegexpLiteral:
  EnforcedStyle: slashes
  SupportedStyles:
    - slashes
    - percent_r
  AllowInnerSlashes: false

Style/StructInheritance:
  Exclude:
    - 'app/models/independent_studio.rb'

Style/PerlBackrefs:
  Enabled: false
