inherit_from: .rubocop_todo.yml
AllCops:
  # Only runs checks on specific directories. Could be expanded to
  # include more directories.
  Include:
    - app/**
    - spec/**
    - features/**
  Exclude:
    - '**/*.sh'
    - '**/*.bash'
    - '**/*.yml'
    - '**/*.txt'
    - '**/*.md'
    - 'bin/spring'
    - db/schema.rb
    - db/migrate/**/*
    - spec/*.opts
    - tmp/**/*
    - vendor/**/*
    - log/**/*
    - app/lib/app_config.rb
    - config/initializers/setup_email_lists.rb
    - features/step_definitions/factory_steps.rb

Rails:
  Enabled: true

Rails/DynamicFindBy:
  Exclude:
    - 'app/models/user_session.rb'

Metrics/AbcSize:
  Max: 38

Metrics/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 50

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - app/services/search/indexer.rb

Style/RegexpLiteral:
  EnforcedStyle: slashes
  SupportedStyles:
    - slashes
    - percent_r
  AllowInnerSlashes: false

Metrics/CyclomaticComplexity:
  Max: 10

Rails/FilePath:
  Exclude:
    - config/environments/test.rb

Rails/TimeZone:
  Exclude:
    - tztest.rb

Style/PerlBackrefs:
  Enabled: false
