AllCops:
  # Only runs checks on specific directories. Could be expanded to
  # include more directories.
  Includes:
    - app/**
    - spec/**
    - features/**
Rails:
  Enabled: true

Metrics/LineLength:
  Max: 150

Style/Documentation:
  Enabled: false