AllCops:
  # Only runs checks on specific directories. Could be expanded to
  # include more directories.
  Include:
    - app/**
    - spec/**
    - features/**
Rails:
  Enabled: true

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 175

Metrics/MethodLength:
  Max: 50

Style/Documentation:
  Enabled: false
