inherit_from: .rubocop_todo.yml
AllCops:
  # Only runs checks on specific directories. Could be expanded to
  # include more directories.
  Include:
    - app/**
    - spec/**
    - features/**
  Exclude:
    - db/schema.rb
    - db/migrate/**/*.rb
    - spec/*.opts
Rails:
  Enabled: true

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 50

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
