require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  # Only runs checks on specific directories. Could be expanded to
  # include more directories.
  TargetRubyVersion: 2.5

  Exclude:
    - .spec
    - Capfile
    - Gemfile
    - Guardfile
    - Rakefile
    - bin/**/*
    - '**/*.sh'
    - '**/*.bash'
    - '**/*.yml'
    - '**/*.txt'
    - '**/*.md'
    - 'bin/**'
    - node_modules/**/*
    - config/boot.rb
    - db/schema.rb
    - db/migrate/**/*
    - spec/*.opts
    - tmp/**/*
    - vendor/**/*
    - log/**/*
    - lib/tasks/mau.rake
    - lib/tasks/debug.rake
    - app/lib/app_config.rb
    - config/initializers/setup_email_lists.rb
    - features/step_definitions/factory_steps.rb
    - features/step_definitions/shared_steps.rb
    - features/step_definitions/user_steps.rb

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/DeprecatedOpenSSLConstant:
  Enabled: true 

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/SuppressedException:
  Exclude:
    - lib/tasks/*.rake
    - app/services/search/indexer.rb

Metrics/AbcSize:
  Max: 38

Metrics/BlockLength:
  Max: 151
  Exclude:
    - config/routes.rb

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 10

Layout/LineLength:
  Max: 150

Metrics/MethodLength:
  Max: 50

Metrics/PerceivedComplexity:
  Max: 9

Naming/AccessorMethodName:
  Exclude:
    - app/models/concerns/address_mixin.rb

Naming/ConstantName:
  Exclude:
    - config/application.rb

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: optional
  Exclude:
    - app/controllers/**/*.rb
    - spec/support/**/*.rb

Rails/FilePath:
  Exclude:
    - config/environments/test.rb

Rails/DynamicFindBy:
  Exclude:
    - app/models/user_session.rb
    - app/presenters/admin_email_list.rb
    - app/services/open_studios_event_service.rb
    - app/services/open_studios_migrator.rb
    - app/services/site_statistics.rb
    - spec/services/open_studios_event_service_spec.rb

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/Output:
  Exclude:
    - config/environments/test.rb
    - 'db/sample_data.rb'
    - 'db/sample_data/**/*'

Rails/OutputSafety:
  Enabled: false

Rails/TimeZone:
  Exclude:
    - tztest.rb

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/ExponentialNotation:
  Enabled: true

Style/FormatStringToken:
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf
  SupportedStyles:
    - sprintf
    - format
Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/RegexpLiteral:
  EnforcedStyle: slashes
  SupportedStyles:
    - slashes
    - percent_r
  AllowInnerSlashes: false

Style/SlicingWithRange:
  Enabled: true

Style/StructInheritance:
  Exclude:
    - 'app/models/independent_studio.rb'

Style/PerlBackrefs:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma


