inherit_from: .rubocop_todo.yml
AllCops:
  # Only runs checks on specific directories. Could be expanded to
  # include more directories.
  Include:
    - app/**
    - spec/**
    - features/**
  Exclude:
    - db/schema.rb
    - db/migrate/**/*.rb
    - spec/*.opts
    - vendor/**
    - app/lib/app_config.rb
    - config/initializers/setup_email_lists.rb
    - features/step_definitions/factory_steps.rb

Rails:
  Enabled: true

Metrics/AbcSize:
  Max: 38

Metrics/LineLength:
  Max: 150

Metrics/ClassLength:
  Max: 300

Metrics/MethodLength:
  Max: 50

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
