// Generated by CoffeeScript 1.12.7
(function() {
  describe('mau.services.objectRoutingService', function() {
    var svc;
    svc = null;
    beforeEach(module('mau.services'));
    beforeEach(inject(function(objectRoutingService) {
      return svc = objectRoutingService;
    }));
    describe('#artistPath', function() {
      it('returns the right path for an artist with an id', function() {
        return expect(svc.artistPath({
          id: 'whatever'
        })).toEqual('/artists/whatever');
      });
      it('returns the right path for an artist with an slug', function() {
        return expect(svc.artistPath({
          slug: 'whatever'
        })).toEqual('/artists/whatever');
      });
      return it('returns the right path for an id', function() {
        return expect(svc.artistPath('whatever')).toEqual('/artists/whatever');
      });
    });
    describe('#studioPath', function() {
      it('returns the right path for an artist with an id', function() {
        return expect(svc.studioPath({
          id: 'whatever'
        })).toEqual('/studios/whatever');
      });
      it('returns the right path for an artist with an slug', function() {
        return expect(svc.studioPath({
          slug: 'whatever'
        })).toEqual('/studios/whatever');
      });
      return it('returns the right path for an id', function() {
        return expect(svc.studioPath('whatever')).toEqual('/studios/whatever');
      });
    });
    return describe('#artPiecePath', function() {
      it('returns the right path for an artist with an id', function() {
        return expect(svc.artPiecePath({
          id: 'whatever'
        })).toEqual('/art_pieces/whatever');
      });
      it('returns the right path for an artist with an slug', function() {
        return expect(svc.artPiecePath({
          slug: 'whatever'
        })).toEqual('/art_pieces/whatever');
      });
      return it('returns the right path for an id', function() {
        return expect(svc.artPiecePath('whatever')).toEqual('/art_pieces/whatever');
      });
    });
  });

}).call(this);
