// Generated by CoffeeScript 1.12.7
(function() {
  describe("OsKeyGenerator", function() {
    beforeEach(function() {
      fixture.set(
        "<div id=\"fixture\">\n  <form class='js-os-key-gen'>\n    <input id='start_date'></input>\n    <input id='end_date'></input>\n    <input id='os_key'></input>\n  </form>\n</div>"
      );
      return jQuery("#fixture input").val("");
    });
    return describe("initialization", function() {
      it("sets the key if the start date is set", function() {
        jQuery("#start_date").val("1 January 2012");
        new MAU.OsKeyGenerator(jQuery("form.js-os-key-gen"), {
          start_date_field: "#start_date",
          end_date_field: "#end_date",
          key_field: "#os_key"
        });
        return expect(jQuery("#fixture #os_key").val()).toEqual("201201");
      });
      it("does not set the key if start date is empty", function() {
        new MAU.OsKeyGenerator(jQuery("form.js-os-key-gen"), {
          start_date_field: "#start_date",
          end_date_field: "#end_date",
          key_field: "#os_key"
        });
        return expect(jQuery("#fixture #os_key").val()).toEqual("");
      });
      return it("does not set the key if start date is an invalid date", function() {
        jQuery("#start_date").val("whatever, yo");
        new MAU.OsKeyGenerator(jQuery("form.js-os-key-gen"), {
          start_date_field: "#start_date",
          end_date_field: "#end_date",
          key_field: "#os_key"
        });
        return expect(jQuery("#fixture #os_key").val()).toEqual("");
      });
    });
  });
}.call(this));
