version: 2
jobs:
  build:
    environment:
      DATABASE_URL: "postgres://ubuntu@localhost/circle_ruby_test"
      DISABLE_SPRING: true
      RAILS_ENV: test
      RACK_ENV: test
      CI: true

    docker:
      - image: circleci/ruby:2.5.1-node-browsers
      - image: circleci/mysql:5.7.19
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
        environment:
          TEST_CLUSTER_NODES: 1

    steps:
      - checkout
      - restore_cache:
          keys:
            # This branch if available
            - v2-dep-{{ .Branch }}-
            # Default branch if not
            - v2-dep-development-
            # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch set properly
            - v2-dep-
      - run:
          shell: /bin/bash
          name: Machine Setup
          command: |-
            sudo gem install bundle rake
      - run:
          shell: /bin/bash
          name: Bundle install
          command: |-
            bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
            bundle exec bundle-audit update && bundle exec bundle-audit check
          environment:
            NODE_ENV: test
            RAILS_ENV: test
      - run:
          shell: /bin/bash
          name: DB Setup and Assets compilation
          command: |-
            bundle exec rake db:schema:load db:seed
            bundle exec rake assets:precompile
          environment:
            NODE_ENV: test
            RAILS_ENV: test
      - run:
          name: Ruby Tests (rspec)
          command: |-
            bundle exec rspec --format doc --format RspecJunitFormatter --out test-results/rspec/results.xml
          environment:
            NODE_ENV: test
            RAILS_ENV: test
      - run:
          name: Cucumber
          command: |-
            bundle exec cucumber --format doc --format RspecJunitFormatter --out test-results/cucumber/results.xml
          environment:
            NODE_ENV: test
            RAILS_ENV: test
      - save_cache:
          key: v2-dep-{{ .Branch }}-{{ epoch }}
          paths:
            - vendor/bundle
      - store_artifacts:
          path: ./tmp/capybara
      - store_artifacts:
          path: ./test-results/rspec
          path: ./test-results/cucumber
      - store_test_results:
          path: ./test-results/rspec
          path: ./test-results/cucumber
  # lint_and_js_tests:
  #   docker:
  #     - image: circleci/ruby:2.5.1-node-browsers
  #   steps:
  #     - checkout
  #     - restore_cache:
  #         keys:
  #           # This branch if available
  #           - v2-dep-{{ .Branch }}-
  #           # Default branch if not
  #           - v2-dep-development-
  #           # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch set properly
  #           - v2-dep-
  #     - run:
  #         shell: /bin/bash
  #         name: Setup
  #         command: |-
  #           sudo gem install bundle rake
  #           bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3
  #           yarn install
  #         environment:
  #           NODE_ENV: test
  #           RAILS_ENV: test
  #     - run:
  #         name: I18n Validate, JS tests and Linters
  #         command: |-
  #           bundle exec rake jest:test i18n:validate js:lint rubocop
  #         environment:
  #           NODE_ENV: test
  #           RAILS_ENV: test
  #     - save_cache:
  #         key: v2-dep-{{ .Branch }}-{{ epoch }}
  #         paths:
  #           - vendor/bundle
  #           - ./node_modules

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
