Time::DATE_FORMATS[:pickadate] = '%d %B, %Y'
Time::DATE_FORMATS[:admin] = '%Y-%m-%d %H:%M%p'
Time::DATE_FORMATS[:admin_date_only] = '%Y-%m-%d'
Time::DATE_FORMATS[:os_day] = '%b %d'
Time::DATE_FORMATS[:time_with_zone] = '%l:%M%P %Z'
Time::DATE_FORMATS[:time_only] = '%l:%M%P'
