// Generated by CoffeeScript 1.12.7
import jQuery from "jquery";

const defaultOpts = {
  start_date_field: "#open_studios_event_start_date",
  key_field: "#open_studios_event_key",
};

class OsKeyGenerator {
  constructor(element, opts) {
    this.element = jQuery(element);
    this.opts = { ...defaultOpts, ...opts };
    const startDate = this.element.find(this.opts.start_date_field);
    this.key = this.element.find(this.opts.key_field);
    startDate.on("change", this.updateKey.bind(this));

    this.updateKey();
  }

  updateKey(_ev) {
    const startDateField = this.element.find(this.opts.start_date_field);
    const datePicker = startDateField.pickadate("picker");
    if (datePicker) {
      this.key.val(datePicker.get("select", "yyyymm"));
    }
  }
}

export default OsKeyGenerator;
