import jQuery from "jquery";

window.jQuery = jQuery;
window.$ = jQuery;

import "lodash/lodash";
import "angular/angular";
import "@components/angular_modules";
import "angular-resource";
import "angular-sanitize";
import "angular-animate";
import "./vendor/angular-mailchimp";
import "angular-ui-utils/modules/keypress/keypress";
import "re-tree";
import "ua-device-detector";
import "ng-device-detector";
import "ng-dialog/js/ngDialog";
import "./templates";

import "@components/notify_mau/notify_mau.js";
import "@components/art_pieces_browser/art_pieces_browser.js";
import "@components/search_results/search_hit.js";
import "@components/search_results/search_results.js";
import "@components/credits_link/credits_link.js";
import "@components/angular_modules.js";
import "@components/admin/email_list_manager/email_list_manager.js";
import "@components/admin/events_notification_bell/events_notification_bell.js";
import "@components/medium/medium.js";
import "@components/social_buttons/share_button.js";
import "@components/social_buttons/favorite_this.js";
import "@components/background-img/background-img.js";
import "@components/mailer/mailer.js";
import "@components/models/email.js";
import "@components/art_piece_tag/art_piece_tag.js";
import "@components/time_ago/time_ago.js";
import "@components/repeater_delimiter/repeater_delimiter.js";
import "@components/image_fader/image_fader.js";
import "@components/password_strength/passwordStrength.directive.js";
import "@components/services/email_changed_events_service.js";
import "@components/services/object_routing_service.js";
import "@components/services/notification_service.js";
import "@components/services/tag_service.js";
import "@components/services/currentUserService.js";
import "@components/services/studios_service.js";
import "@components/services/mailer_service.js";
import "@components/services/favorites_service.js";
import "@components/services/env_service.js";
import "@components/services/email_lists_service.js";
import "@components/services/art_pieces_service.js";
import "@components/services/artists_service.js";
import "@components/services/open_studios_registration_service.js";
import "@components/services/search_service.js";
import "@components/services/emails_service.js";
import "@components/services/application_events_service.js";
import "@components/link_if/link_if.js";
import "@components/open_studios_registration_widget/open_studios_registration_widget.js";
import "@components/editable_content/editable_content.js";

import "./mau/feedback.js";
import "./mau/gto/all_tabs.js";
import "./mau/gto/art_piece_form.js";
import "./mau/gto/artists.js";
import "./mau/gto/main.js";
import "./mau/gto/map.js";
import "./mau/gto/navigation.js";
import "./mau/gto/users.js";
import "./mau/jquery/arrange_art.js";
import "./mau/jquery/jquery.isOverflowing.js";
import "./mau/jquery/jquery.feedback";
import "./mau/mau.js";
import "./mau/mau_discount.js";
import "./mau/mau_user_account_chooser.js";
import "./mau/paypal.js";
import "./mau/sampler.js";
import "./mau/whats_this_popup.js";

import "./vendor/angularSlideables";
import "./mau_app";
import "selectize/dist/js/standalone/selectize";
import "./vendor/bootstrap/transition";
import "./vendor/bootstrap/tab";
import "./vendor/bootstrap/collapse";
import "pickadate/lib/picker";
import "pickadate/lib/picker.date";
import "pickadate/lib/picker.time";

import ujs from "@rails/ujs";
ujs.start();
