import jQuery from "jquery";

window.jQuery = jQuery;
window.$ = jQuery;

import "select2";
import "angular/angular";
import "@angularjs/angular_modules";
import "angular-resource";
import "angular-sanitize";
import "angular-animate";
import "./vendor/angular-mailchimp";
import "angular-ui-utils/modules/keypress/keypress";
import "re-tree";
import "ng-dialog/js/ngDialog";
import "@components/notify_mau/notify_mau";
import "@components/art_pieces_browser/art_pieces_browser";
import "@components/medium/medium";
import "@components/social_buttons/share_button";
import "@components/social_buttons/favorite_this";
import "@components/background-img/background-img";
import "@components/art_piece_tag/art_piece_tag";
import "@components/repeater_delimiter/repeater_delimiter";
import "@components/link_if/link_if";
import "@angularjs/services/object_routing.service";
import "@angularjs/services/notification.service";
import "@angularjs/services/favorites.service";
import "@angularjs/services/env.service";
import "./app/feedback";
import "./app/flash_binding";
import "./app/all_tabs";
import "./app/map";
import "./app/jquery/jquery.feedback";
import "./app/jquery/jquery.isOverflowing";
import "./mau_app";
import "./vendor/bootstrap/transition";
import "./vendor/bootstrap/tab";
import "./vendor/bootstrap/collapse";
import "./globals";
import "@reactjs";

import ujs from "@rails/ujs";
ujs.start();
