# config for mau
# 
# note : no tabs and indent is ipmortant.
test:
   site_url: localhost:3000
   cache_server: localhost:11211
   image_servers: 
   cache_ns: tst
   feedback_emails: 
   mailchimp_api_key: bogus-key
   oslive: 201110

ub:
   site_url: localhost:3000
   cache_server: localhost:11211
   image_servers: 
   cache_ns: ub
   cache_expiry:
       feed: 5
       search: 20
       objects: 20
       media_frequency: 3600
       tag_frequency: 3600
   # minimum artists before we show a studio

local:
   site_url: localhost:3000
   cache_server: localhost:11211
   image_servers: 
   cache_ns: lcl
   cache_expiry:
       feed: 20
       search: 20
       objects: 20
       media_frequency: 3600
       tag_frequency: 3600
   mailchimp_api_key: 20b864bd196695dda00c0ea3dcba8534-us2

development:
   site_url: artistsdev.missionartistsunited.org
   cache_server: localhost:11211
   image_servers: 
   cache_ns: dev
   cache_expiry:
       feed: 300
       search: 20
       objects: 0
       media_frequency: 3600
       tag_frequency: 3600
   mailchimp_api_key: 20b864bd196695dda00c0ea3dcba8534-us2

production:
   feedback_emails:
      - feedback@missionartistsunited.org
      - maufeedback@bunnymatic.com
      - trish@trishtunney.com
   site_url: www.missionartistsunited.org
   cache_server: localhost:11211
   image_servers: 
      - http://img1.missionartistsunited.org
      - http://img2.missionartistsunited.org
   cache_ns: 
   cache_expiry:
       feed: 3600
       search: 300
       objects: 0
       media_frequency: 3600
       tag_frequency: 3600

#     - feed: http://twitter.com/statuses/user_timeline/56806324.json
#       url: http://twitter.com/SevillaGranger 
common:
   feedback_emails:
      - feedback@missionartistsunited.org
      - maufeedback@bunnymatic.com
   cache_expiry:
       feed: 300
       search: 20
       objects: 
       media_frequency: 3600
       tag_frequency: 3600

   yahoo_api_key: N.34cqHV34HBVzs_fNwThGrKQN8oMtEsizMOW14GriC2lceN7KrJKTklkpO2uUDX
   shop_url: http://www.cafepress.com/MissionArtists
   # minimum artists before we show a studio
   min_artists_per_studio: 0
   autosuggest:
     tags:
       cache_expiry: 300
       cache_key: tagsuggest
     artist_names:
       # expire daily
       cache_expiry: 86400
       cache_key: artistnamesuggest
   oslive: 201204
   accepting_flaxshow_submissions: false
   mailchimp_api_key: 459d90c2e137cfb3c28a545e4439a285-us2