# config for mau
# 
# note : no tabs and indent is ipmortant.
test:
   site_url: localhost:3000
   cache_server: localhost:11211
   image_servers: 
   cache_ns: tst
   feedback_emails: 


ub:
   site_url: localhost:3000
   cache_server: localhost:11211
   image_servers: 
   cache_ns: ub
   cache_expiry:
       feed: 5
       search: 20
       objects: 20
       media_frequency: 3600
       tag_frequency: 3600
   # minimum artists before we show a studio

local:
   site_url: localhost:3000
   cache_server: localhost:11211
   image_servers: 
   cache_ns: lcl
   cache_expiry:
       feed: 20
       search: 20
       objects: 20
       media_frequency: 3600
       tag_frequency: 3600

development:
   site_url: artistsdev.missionartistsunited.org
   cache_server: localhost:11211
   image_servers: 
   cache_ns: dev
   cache_expiry:
       feed: 300
       search: 20
       objects: 0
       media_frequency: 3600
       tag_frequency: 3600

production:
   feedback_emails:
      - feedback@missionartistsunited.org
      - maufeedback@bunnymatic.com
      - trish@trishtunney.com
   site_url: www.missionartistsunited.org
   cache_server: localhost:11211
   image_servers: 
      - http://img1.missionartistsunited.org
      - http://img2.missionartistsunited.org
   cache_ns: 
   cache_expiry:
       feed: 3600
       search: 300
       objects: 0
       media_frequency: 3600
       tag_frequency: 3600

common:
   feedback_emails:
      - feedback@missionartistsunited.org
      - maufeedback@bunnymatic.com
   cache_expiry:
       feed: 300
       search: 20
       objects: 
       media_frequency: 3600
       tag_frequency: 3600
   feeds_urls: 
      - feed: http://risingartist.blogspot.com/feeds/posts/default?alt=rss
        url: http://risingartist.blogspot.com/
      - feed: http://missionlocal.org/category/the-arts/feed/
        url: http://missionlocal.org/category/the-arts/
      - feed: http://twitter.com/statuses/user_timeline/62131363.json
        url: http://twitter.com/sfmau 
      - feed: http://twitter.com/statuses/user_timeline/56806324.json
        url: http://twitter.com/SevillaGranger 
      - feed: http://twitter.com/statuses/user_timeline/32943864.json
        url: http://twitter.com/bunnymaticsf
      - feed: http://sfartnews.wordpress.com/feed/
        url: http://sfartnews.wordpress.com/ 
      - feed: http://trishtunney.blogspot.com/feeds/posts/default?alt=rss
        url: http://trishtunney.blogspot.com/
      - feed: http://catherine-mackey.blogspot.com/feeds/posts/default?alt=rss
        url: http://catherine-mackey.blogspot.com/
      - feed: http://apaintingaday.blogspot.com/feeds/posts/default?alt=rss
        url: http://apaintingaday.blogspot.com/
      - feed: http://katjaleibenath.blogspot.com/feeds/posts/default?alt=rss
        url: http://katjaleibenath.blogspot.com
      - feed: http://estudiomartita.blogspot.com/feeds/posts/default?alt=rss
        url: http://estudiomartita.blogspot.com/
      - feed: http://clarussell.blogspot.com/feeds/posts/default?alt=rss
        url: http://clarussell.blogspot.com/
   yahoo_api_key: N.34cqHV34HBVzs_fNwThGrKQN8oMtEsizMOW14GriC2lceN7KrJKTklkpO2uUDX
   shop_url: http://www.cafepress.com/MissionArtists
   # minimum artists before we show a studio
   min_artists_per_studio: 0
   autosuggest:
       cache_expiry: 300
       cache_key: tagsuggest
   oslive: false
