# config for mau
# 
# note : no tabs and indent is ipmortant.
test:
   site_url: test.missionartistsunited.org
   #image_servers: 
   mailchimp_api_key: bogus-key
   oslive: 201210
   min_artists_per_studio: 1

development:
   site_url: mau.rcode5.com
   #image_servers: 
   cache_expiry:
       feed: 300
       search: 20
       objects: 0
       media_frequency: 3600
       tag_frequency: 3600
       new_art: 300
   oslive: 201404

acceptance:
   site_url: acceptance.missionartistsunited.com

production:
   site_url: missionartistsunited.org
   #image_servers: 
   cache_expiry:
       feed: 3600
       search: 300
       objects: 0
       media_frequency: 3600
       tag_frequency: 3600
       new_art: 86400

common:
   cache_server: localhost:11211

   feedback_emails:
      - feedback@missionartistsunited.org
      - maufeedback@bunnymatic.com
   cache_expiry:
       feed: 300
       search: 20
       objects: 
       media_frequency: 3600
       tag_frequency: 3600
       new_art: 300

   shop_url: http://www.cafepress.com/MissionArtists
   # minimum artists before we show a studio
   min_artists_per_studio: 0
   autosuggest:
     tags:
       cache_expiry: 300
       cache_key: tagsuggest
     artist_names:
       # expire daily
       cache_expiry: 86400
       cache_key: artistnamesuggest
   oslive: 201410
   accepting_flaxshow_submissions: false
   open_studios_event_keys:
      - 201004
      - 201010
      - 201104
      - 201110
      - 201204
      - 201210
      - 201304
      - 201310
      - 201404
