# config for mau
#
# note : no tabs and indent is ipmortant.
test:
  mailchimp_api_key: bogus-key
  min_artists_per_studio: 1
  features:
    virtual_open_studios: true
  pagination:
    media:
      per_page: 12
    tags:
      per_page: 12
    artists:
      per_page: 12

development:
  features:
    virtual_open_studios: true
  cache_expiry:
    feed: 300
    search: 20
    objects: 0
    new_art: 300
  pagination:
    artists:
      per_page: 5
    media:
      per_page: 12
    tags:
      per_page: 12

acceptance:
  features:
    virtual_open_studios: true
  S3_DOMAIN: 'us-west-1'

production:
  cache_expiry:
    feed: 3600
    search: 300
    objects: 0
    new_art: 86400

common:
  event_time_zone: America/Los_Angeles
  open_studios_help_document_url: https://bit.ly/v-openstudios
  features:
    virtual_open_studios: false
  pagination:
    media:
      per_page: 24
    tags:
      per_page: 24
    artists:
      per_page: 28
  social_links:
    facebook: http://www.facebook.com/MissionArtists
    twitter: http://www.twitter.com/sfmau
    instagram: https://www.instagram.com/missionartists
    pinterest: http://pinterest.com/mausf/

  cache_server: localhost:11211
  signup_secret_word: eat-shit-hackers
  cache_expiry:
    feed: 300
    search: 20
    objects:
    new_art: 300

  shop_url: http://www.cafepress.com/MissionArtists
  # minimum artists before we show a studio
  min_artists_per_studio: 0
  autosuggest:
    tags:
      cache_expiry: 300
      cache_key: tagsuggest
    artist_names:
      # expire daily
      cache_expiry: 86400
      cache_key: artistnamesuggest
  ga_key: blah
  google_map_api_key: key
  ga_server_api_key: server_key
  POSTMARK_API_KEY: bogus
  mailchimp_api_key: bogus
  mailchimp_artist_list_id: f8d679dde8
  mailchimp_fan_list_id: 041ae187df
  messaging_server:
  messaging_token:
  recaptcha_private_key: bogus
  recaptcha_public_key: bogus
