# config for mau
# 
# note : no tabs and indent is ipmortant.
test:
   site_url: test.missionartistsunited.org
   cache_server: localhost:11211
   #image_servers: 
   mailchimp_api_key: bogus-key
   oslive: 201210
   min_artists_per_studio: 1

development:
   recaptcha_public_key: 6LfgJ9oSAAAAAHDQ_PRgG60sIXtOjH3aWcp__Dav
   recaptcha_private_key: 6LfgJ9oSAAAAAELX8fI1cHywuLFikg7komNUkM_V
   site_url: mau.rcode5.com
   cache_server: localhost:11211
   #image_servers: 
   cache_expiry:
       feed: 300
       search: 20
       objects: 0
       media_frequency: 3600
       tag_frequency: 3600
       new_art: 300
   mailchimp_api_key: 20b864bd196695dda00c0ea3dcba8534-us2
   oslive: 201310

production:
   site_url: missionartistsunited.org
   cache_server: localhost:11211
   #image_servers: 
   cache_expiry:
       feed: 3600
       search: 300
       objects: 0
       media_frequency: 3600
       tag_frequency: 3600
       new_art: 86400
   messaging_server: 'http://mau-messages.herokuapp.com:80/maumessages'
   messaging_token: 'traemosekamog'

common:
   recaptcha_public_key: 6Lc9BNkSAAAAAOmI_O3g_I9ky4IFIdHnY7YDU3Gc
   recaptcha_private_key: 6Lc9BNkSAAAAAAHJ-NxXih62VuSsqnUx3EJc91Bo

   show_lightbox_feature: true
   feedback_emails:
      - feedback@missionartistsunited.org
      - maufeedback@bunnymatic.com
   cache_expiry:
       feed: 300
       search: 20
       objects: 
       media_frequency: 3600
       tag_frequency: 3600
       new_art: 300

   yahoo_api_key: N.34cqHV34HBVzs_fNwThGrKQN8oMtEsizMOW14GriC2lceN7KrJKTklkpO2uUDX
   shop_url: http://www.cafepress.com/MissionArtists
   # minimum artists before we show a studio
   min_artists_per_studio: 0
   autosuggest:
     tags:
       cache_expiry: 300
       cache_key: tagsuggest
     artist_names:
       # expire daily
       cache_expiry: 86400
       cache_key: artistnamesuggest
   oslive: 201310
   accepting_flaxshow_submissions: false
   mailchimp_api_key: 459d90c2e137cfb3c28a545e4439a285-us2
   ga_key: UA-11097408-3
   ga_api_key: AIzaSyDEsN3CF30SVYHrCTleSPe_EaERFvIRXnU
   # old key
   #ABQIAAAAbD_lhY5wFaR_9YsyMHgo_hQ5DYjH_N4HA24Iofus6u_r9JmbOBQYZL9AmYmNhPcGegikfkMM9BY-Ng
   #AIzaSyDEsN3CF30SVYHrCTleSPe_EaERFvIRXnU
   open_studios_event_keys:
      - 201004
      - 201010
      - 201104
      - 201110
      - 201204
      - 201210
      - 201304
      - 201310
