<%
std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'pretty'} --strict --order random"
data = ''
if (File.exist? "./.env.test")
  data = File.open('./.env.test','r').read.split.join(" ")
end
std_opts += " " + data %>
default: <%= std_opts %> features
rerun: "--format rerun --out failed-feature-examples.txt"
