# MySQL
local:
  adapter: mysql
  encoding: utf8
  database: mau_dev
  username: mauadmin
  password: MrMau415
  host: localhost

ub:
  adapter: mysql
  encoding: utf8
  database: mau_dev
  username: mauadmin
  password: MrMau415
  host: localhost

development:
  adapter: mysql
  encoding: utf8
  database: mau_dev
  username: root
  #username: mauadmin
  #password: MrMau415
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: mau_test
  username: root
  password: 
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: mau
  username: mauadmin
  password: MrMau415
