# MySQL
development: &dev
  adapter: mysql2
  encoding: utf8
  database: mau_dev
  username: root
  password:
  host: localhost

test: &test
  adapter: mysql2
  encoding: utf8
  database: mau_test
  username: root
  password: 
  host: localhost


cucumber:
  <<: *test
