# MySQL
local:
  adapter: mysql2
  encoding: utf8
  database: mau_dev
  username: mauadmin
  password: MrMau415
  host: localhost

ub:
  adapter: mysql2
  encoding: utf8
  database: mau_dev
  username: mauadmin
  password: MrMau415
  host: localhost

development:
  adapter: mysql2
  encoding: utf8
  database: mau_dev
  username: mauadmin
  password: MrMau415
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: mau_test
  username: mauadmin
  password: MrMau415
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: missiona_prod
  username: missiona_mau
  password: Zo0Tdha0sXTWD9Qji
