inherit_from: ../.rubocop.yml

Metrics/BlockLength:
  Max: 600

Rails/OutputSafety:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: true
  Exclude:
    - '**/*'

Lint/SuppressedException:
  Exclude:
    - 'support/**/*'

Lint/RescueException:
  Exclude:
    - 'support/**/*'
