inherit_from: ../.rubocop.yml

Metrics/BlockLength:
  Max: 600

Rails/OutputSafety:
  Enabled: false

Lint/HandleExceptions:
  Exclude:
    - 'support/**/*'
Lint/RescueException:
  Exclude:
    - 'support/**/*'
