#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/boot'
Rails::Initializer.run do |config|
end

# add studios
def add_studio(name, st, city, state, zip, url)
  if not Studio.find_by_name(name)
    st = Studio.new do |s|
      s.name = name
      s.street = st
      s.city = city
      s.state = state
      s.zip = zip
      s.url = url
    end
    st.save 
    st.id
  else
    puts "Studio " + name + " has already been added"
  end
end

def add_medium(name)
  if not Medium.find_by_name(name)
    Medium.new(:name=>name).save
  else
    puts "Medium " + name + " has already been added"
  end
end

#### 
#  main routine
#  

puts "Adding studios"
# name, street, city, state, zip, url
 add_studio("1890 Bryant St Studios", "1890 Bryant St", "San Francisco", "CA", "94110", "http://www.1890bryant.com")
 add_studio("ActivSpace","3150 18th Street, #102", "San Francisco", "CA", "94110", "http://activspace.com")

 add_studio("The Blue Studio","2111 Mission St", "San Francisco", "CA", "94110", "http://thebluestudio.org")
 add_studio("Developing Environments","540 Alabama St", "San Francisco", "CA", "94110", "http://www.lightdark.com/deweb/index.html")
 add_studio("Project Artaud","499 Alabama Street",  "San Francisco", "CA", "94110", "http://artaud.org")
 add_studio("Workspace Limited","2150 Folsom St",  "San Francisco", "CA", "94110", "http://workspacelimited.org")


puts "Adding media"
 add_medium('Drawing')
 add_medium('Mixed-Media')
 add_medium('Photography')
 add_medium('Glass/Ceramics')
 add_medium('Printmaking')
 add_medium('Painting - Oil')
 add_medium('Painting - Acrylic')
 add_medium('Painting - Watercolor')
 add_medium('Sculpture')
 add_medium('Jewelry')
 add_medium('Fiber/Textile')
 add_medium('Furniture')
 add_medium('Books') 
