inherit_from: ../.rubocop.yml

Lint/Debugger:
  Exclude:
    - 'step_definitions/**/*'

Lint/AmbiguousRegexpLiteral:
  Exclude:
    - 'step_definitions/**/*'

Lint/SuppressedException:
  Exclude:
    - 'support/**/*'

Lint/RescueException:
  Exclude:
    - 'support/**/*'
